app:
    name: yjblog
server:
    port: 8080
spring:
    profiles:
        # 默认激活 dev 环境
        active: dev
# 添加了配置了，不再使用以下配置
#    jackson:
#        # 设置后台返参，若字段值为 null, 则不返回
#        default-property-inclusion: non_null
#        # 设置日期字段格式
#        date-format: yyyy-MM-dd HH:mm:ss

jwt:
    # 签发人
    issuer: yjblog
    # 秘钥
    secret: jElxcSUj38+Bnh73T68lNs0DfBSit6U3whQlcGO2XwnI+Bo3g4xsiCIPg8PV/L0fQMis08iupNwhe2PzYLB9Xg==
    # token 过期时间（单位：分钟） 24*60
    tokenExpireTime: 1440
    # token 请求头中的 key 值
    tokenHeaderKey: Authorization
    # token 请求头中的 value 值前缀
    tokenPrefix: Bearer